############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Blog"
pageRef = "/blog"
weight = 2

[[main]]
name = "Contact"
pageRef = "/contact"
weight = 3

# footer menu

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
